// app/components/AButton.tsx
export default function AButton({
    children,
    ...rest
}: {
    children: React.ReactNode;
} & React.ButtonHTMLAttributes<HTMLButtonElement>) {
    return (
        <button
            {...rest}
            className="
                h-9
                bg-blue-700
                rounded-md
                cursor-pointer
                disabled:bg-gray-500
                disabled:cursor-not-allowed"
        >
            {children}
        </button>
    );
}

// src/lib/components/AButton.svelte
<script>
    let { children, ...btnProps } = $props();
</script>

<button
    {...btnProps}
    class=" h-9
                bg-blue-700
                rounded-md
                cursor-pointer
                disabled:bg-gray-500
                disabled:cursor-not-allowed"
>
    {@render children?.()}
</button>
